services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '56605:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge


