spring:
  datasource:
    url: jdbc:postgresql://localhost:56605/postgres
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # or create-drop for development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  security:
    user:
      name: testuser
      password: testpass




server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always


logging:
  level:
    com.sheffmachine.kotlinbootproject: DEBUG
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

