spring:
  datasource:
    url: jdbc:postgresql://localhost:56605/postgres
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # or create-drop for development
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.sheffmachine.kotlinbootproject: DEBUG
    org.hibernate.SQL: DEBUG
